// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppBars: typeof import('./src/components/appBars.vue')['default']
    Chart: typeof import('./src/components/panel/chart.vue')['default']
    ChartCustom: typeof import('./src/components/panel/ChartCustom.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    Exchanges: typeof import('./src/components/panel/exchanges.vue')['default']
    Log: typeof import('./src/components/log/index.vue')['default']
    Login: typeof import('./src/components/login/index.vue')['default']
    Logmain: typeof import('./src/components/log/Logmain.vue')['default']
    Panel: typeof import('./src/components/panel/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('./src/components/log/Select.vue')['default']
    Setting: typeof import('./src/components/setting/index.vue')['default']
    Settingmain: typeof import('./src/components/setting/settingmain.vue')['default']
    StateCustom: typeof import('./src/components/panel/stateCustom.vue')['default']
    StrategyConfig: typeof import('./src/components/setting/strategyConfig.vue')['default']
    SysState: typeof import('./src/components/panel/sysState.vue')['default']
    Table: typeof import('./src/components/panel/Table/index.vue')['default']
  }
}
